#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#npm run build:prod
#npm run lint:ts
#npm run lint:scss
#Shouldn't use in precommit and shouldn't screenshot test
#npm run test:unit
#npm run storybook:build
#npm run test:ui:ci